name: core_data
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.2.0
  injectable: ^2.5.1

  core:
    path: ../core

  rxdart: ^0.28.0

flutter:
  assets:
    - assets/photovoltaic_sample.json

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  injectable_generator: ^2.8.1
  build_runner: ^2.11.1

  mockito: ^5.6.3
  fake_async: ^1.3.3
